// day11-react/web729/src/components/Footer/Footer.js
import React, { Component } from 'react'

import './Footer.css'
export default class Footer extends Component {
  allCheckHandle = (e) => {
    const { checked } = e.target
    this.props.getTodosStatus(checked)
  }

  render() {
    const { list } = this.props

    const allTotal = list.length
    const doneTotal = list.filter((item) => item.isDone).length
    return (
      <div className="todo-footer">
        <label>
          <input
            type="checkbox"
            checked={allTotal === doneTotal}
            onChange={this.allCheckHandle}
          />
        </label>
        <span>
          <span>已完成 {doneTotal}</span> / 全部 {allTotal}
        </span>
        <button
          className="btn btn-danger"
          onClick={this.props.deleteAllDoneTodos}
        >
          清除已完成任务
        </button>
      </div>
    )
  }
}

// day24-vue/web0729-vue/src/components/Footer.vue
<template>
  <div class="todo-footer">
    <label>
      <input
        type="checkbox"
        :checked="doneTotal === allTotal"
        @change="allCheckHandle"
      />
    </label>
    <span>
      <span>已完成{{ doneTotal }}</span> / 全部{{ allTotal }}
    </span>
    <button class="btn btn-danger" @click="clearDoneHandle">
      清除已完成任务
    </button>
  </div>
</template>

<script>
export default {
  props: ['list', 'allCheckHandle', 'clearDoneHandle'],
  computed: {
    allTotal() {
      return this.list.length
    },
    doneTotal() {
      return this.list.filter((item) => item.isDone).length
    },
  },
}
</script>

<style>
/*footer*/
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;
}

.todo-footer label {
  display: inline-block;
  margin-right: 20px;
  cursor: pointer;
}

.todo-footer label input {
  position: relative;
  top: -1px;
  vertical-align: middle;
  margin-right: 5px;
}

.todo-footer button {
  float: right;
  margin-top: 5px;
}
</style>
