// day13-react/web729/06-src-hooks-useState&useEffect使用/App.js
import React, { Component } from 'react'
import Count from './components/Count'
export default class App extends Component {
  state = {
    isShow: true,
    count: 99,
  }
  render() {
    return (
      <div>
        {this.state.isShow && <Count num={this.state.count}></Count>}
        <button
          onClick={() => {
            this.setState({
              isShow: false,
            })
          }}
        >
          卸载Count
        </button>
        <button
          onClick={() => {
            this.setState({
              count: this.state.count - 10,
            })
          }}
        >
          app-count减
        </button>
      </div>
    )
  }
}

// day26-vue/web0729-vue/03-src-vuex模块化/App.vue
<template>
  <div>
    <h1>app组件</h1>
    <hr />
    <Count></Count>
    <hr />
    <Test></Test>
  </div>
</template>

<script>
import Count from './components/Count.vue'
import Test from './components/Test.vue'
export default {
  components: {
    Count,
    Test,
  },
}
</script>

<style></style>
