// day24-vue/web0729-vue/src/components/Footer.vue
<template>
  <div class="todo-footer">
    <label>
      <input
        type="checkbox"
        :checked="doneTotal === allTotal"
        @change="allCheckHandle"
      />
    </label>
    <span>
      <span>已完成{{ doneTotal }}</span> / 全部{{ allTotal }}
    </span>
    <button class="btn btn-danger" @click="clearDoneHandle">
      清除已完成任务
    </button>
  </div>
</template>

<script>
export default {
  props: ['list', 'allCheckHandle', 'clearDoneHandle'],
  computed: {
    allTotal() {
      return this.list.length
    },
    doneTotal() {
      return this.list.filter((item) => item.isDone).length
    },
  },
}
</script>

<style>
/*footer*/
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;
}

.todo-footer label {
  display: inline-block;
  margin-right: 20px;
  cursor: pointer;
}

.todo-footer label input {
  position: relative;
  top: -1px;
  vertical-align: middle;
  margin-right: 5px;
}

.todo-footer button {
  float: right;
  margin-top: 5px;
}
</style>

// day14-react/web729/01-src-todos函数组件/components/Footer/Footer.js
import React from 'react'
import PubSub from 'pubsub-js'
import './Footer.css'
export default function Footer(props) {
  const doneTotal = props.list.filter((item) => item.isDone).length
  const allTotal = props.list.length
  return (
    <div className="todo-footer">
      <label>
        <input
          type="checkbox"
          checked={doneTotal === allTotal}
          onChange={(e) => {
            PubSub.publish('allcheck', e.target.checked)
          }}
        />
      </label>
      <span>
        <span>已完成 {doneTotal}</span> / 全部 {allTotal}
      </span>
      <button className="btn btn-danger" onClick={props.clearHandle}>
        清除已完成任务
      </button>
    </div>
  )
}
