// day12-react/web729/04-src-getDerivedStateFromProps/App.js
import React, { Component } from 'react'
import Test from './components/Test'
export default class App extends Component {
  state = {
    count: 0,
  }
  render() {
    return (
      <div>
        <div>{this.state.count}</div>
        <button
          onClick={() => {
            this.setState({ count: this.state.count + 1 })
          }}
        >
          按钮
        </button>
        {this.state.count <= 5 && <Test count={this.state.count}></Test>}
      </div>
    )
  }
}

// day24-vue/web0729-vue/04-src-mixin/App.vue
<template>
  <!-- 用于定义结构: template中至少需要一个根标签 -->
  <div>
    <h1>app组件</h1>
    <!-- <Test></Test> -->
    <Demo></Demo>
  </div>
</template>
<script>
// 写定义组件的代码
// import Test from './components/Test'
import Demo from './components/Demo'
export default {
  data() {
    return {
      count: 0,
    }
  },
  components: {
    // Test,
    Demo,
  },
  mounted() {},
}
</script>
<style></style>
