// day24-vue/web0729-vue/01-src-单文件组件的基本使用/App.vue
<template>
  <!-- 用于定义结构: template中至少需要一个根标签 -->
  <div>
    <h1>app跟组件</h1>
    <div>{{ count }}</div>
    <button @click="handle">按钮</button>
    <hr />
    <test></test>
  </div>
</template>
<script>
import Vue from 'vue'
import test from './components/Test'
// 写定义组件的代码
export default Vue.extend({
  data() {
    return {
      count: 0,
    }
  },
  methods: {
    handle() {
      this.count = this.count + 1
    },
  },
  components: {
    test: test,
  },
})
</script>
<style>
div {
  background-color: pink;
}
</style>

// day12-react/web729/04-src-getDerivedStateFromProps/App.js
import React, { Component } from 'react'
import Test from './components/Test'
export default class App extends Component {
  state = {
    count: 0,
  }
  render() {
    return (
      <div>
        <div>{this.state.count}</div>
        <button
          onClick={() => {
            this.setState({ count: this.state.count + 1 })
          }}
        >
          按钮
        </button>
        {this.state.count <= 5 && <Test count={this.state.count}></Test>}
      </div>
    )
  }
}
