// day26-vue/web0729-vue/03-src-vuex模块化/App.vue
<template>
  <div>
    <h1>app组件</h1>
    <hr />
    <Count></Count>
    <hr />
    <Test></Test>
  </div>
</template>

<script>
import Count from './components/Count.vue'
import Test from './components/Test.vue'
export default {
  components: {
    Count,
    Test,
  },
}
</script>

<style></style>

// day12-react/web729/04-src-getDerivedStateFromProps/App.js
import React, { Component } from 'react'
import Test from './components/Test'
export default class App extends Component {
  state = {
    count: 0,
  }
  render() {
    return (
      <div>
        <div>{this.state.count}</div>
        <button
          onClick={() => {
            this.setState({ count: this.state.count + 1 })
          }}
        >
          按钮
        </button>
        {this.state.count <= 5 && <Test count={this.state.count}></Test>}
      </div>
    )
  }
}
