// day10-react/web729/src/App.js
import React from 'react'
import Son from './components/Son'

function Test() {
  return <h3>我是test组件</h3>
}
// 写一个根组件
export default class App extends React.Component {
  
  // console.log(this)

  state = {
    money: '5毛钱',
  }
  render() {
    return (
      <div id="app">
        <Son ele={<h2>123</h2>} Com={Test} obj={{ name: 'zs' }}></Son>
      </div>
    )
  }
}

// day24-vue/web0729-vue/02-src-ref使用/App.vue
<template>
  <!-- 用于定义结构: template中至少需要一个根标签 -->
  <div>
    <h1 ref="xxx">app组件</h1>
    <Test ref="yyy"></Test>
  </div>
</template>
<script>
// 写定义组件的代码
import Test from './components/Test'
export default {
  components: {
    Test,
  },
  mounted() {
    console.log(this.$refs)
  },
}
</script>
<style></style>
